language: android
dist: trusty

# Environment variables
env:
    global:
        - ANDROID_API_LEVEL=28
        - ANDROID_BUILD_TOOLS_VERSION=28.0.3

# Android SDK and tools configuration
android:
    licenses:
        - 'android-sdk-license-.+'
    components:
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL

# Gradle dependencies caching
before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache

# Build project
before_script:
    - openssl aes-256-cbc -K $encrypted_f97d7a1fd3b8_key -iv $encrypted_f97d7a1fd3b8_iv -in keystore.jks.enc -out keystore.jks -d
    - echo "keystoreFile=keystore.jks" >> gradle.properties
    - echo "keystoreAlias=mainkey" >> gradle.properties
    - echo "keystorePassword=$KEYSTORE_PASS" >> gradle.properties
script:
    - chmod +x ./gradlew
    - ./gradlew bundleSignedRelease
